### ISSUE TITLE
Needs ghc 7 10 2

### ISSUE THREAD

**Issue by endrebak** [bitemyapp/shawty-prime#1]
Got this error:

> Compiler version mismatched, found ghc-7.10.3 (x86_64), but expected minor version match with ghc-7.10.2 (x86_64) (based on resolver setting in /Users/endrebakkenstovner/code/haskell/shawty-prime/stack.yaml).
> Try running "stack setup" to install the correct GHC into /Users/endrebakkenstovner/.stack/programs/x86_64-osx/
> Compiler version mismatched, found ghc-7.10.3 (x86_64), but expected minor version match with ghc-7.10.2 (x86_64) (based on resolver setting in /Users/endrebakkenstovner/code/haskell/shawty-prime/stack.yaml).
> Try running "stack setup" to install the correct GHC into /Users/endrebakkenstovner/.stack/programs/x86_64-osx/

When running `stack setup` the 150 mb ghci (compressed?) starts to dl. Is there a way to make this project work for any ghc version past 7 10 2?

**Comment by bitemyapp** [comment]
Yes, by modifying the `stack.yaml`. You can PR it if you want.
